---
# tasks file for host-registration
# check the os distribution family and version
- name: gather os distribution
  debug: msg="{{ item }}"
  with_items: 
  - "{{ ansible_distribution }}"
  - "{{ ansible_distribution_version }}"
  - "{{ ansible_distribution_major_version }}"

# install python2 if it is not installed
- name: check if the python is alraady installed
  shell: which python
  register: python_installed
  changed_when: false
  ignore_errors: true

- name: install python2 and add make it default in rhel 8 systems if not exixts
  block:
    - name: install python2
      yum:
        name: python2
        state: present

    - name: add python symbolic link to python2
      alternatives:
        name: python
        link: /usr/bin/python
        path: /usr/bin/python2
  when: python_installed.rc == "1" and ansible_distribution_major_version == "8"

# Download the bootstrap script from Satellite server and regidter rhel host
- name: Register to Satellite
  block:
    - name: Download bootstrap script
      get_url: 
        url: "{{ bootstrap_url }}"
        dest: /root/bootstrap.py
        mode: "0755"
        validate_certs: no

    - name: Run bootstrap script
      shell: /root/bootstrap.py -l admin -p {{ Password }} -s {{ Satellite_Server }} -o {{ Satellite_Organization }} -a "RHEL{{ ansible_distribution_major_version }}_AK" -L Default --skip-foreman --force --install-katello-agent --fqdn=$(hostname)
    #   register: bootstrap_log

    # - debug:
    #   msg: "{{ bootstrap_log.stdout }}"
  when: ansible_distribution == "RedHat"
