---
# tasks file for host-registration
# check the os distribution family and version
- name: gather os distribution
  debug: msg="{{ item }}"
  with_items: 
  - "{{ ansible_distribution }}"
  - "{{ ansible_distribution_version }}"
  - "{{ ansible_distribution_major_version }}"

- name: remove rhn subscription from rhel 7 if it exists
  shell: mv /etc/sysconfig/rhn/systemid /root/systemid-bakup
  ignore_errors: true
  when: ansible_distribution_major_version == "7" and ansible_distribution == 'RedHat'

# Download the bootstrap script from Satellite server and register a rhel host
- name: Register to Satellite
  block:
    - name: Download bootstrap script
      get_url: 
        url: "{{ bootstrap_url }}"
        dest: /root/bootstrap.py
        mode: "0755"
        validate_certs: no

    - name: Run bootstrap script
      command:
        argv:
          - "{{ Python }}"
          - /root/bootstrap.py 
          - -l admin
          - -p {{ Satellite6_Password }}
          - -s{{ Satellite_Server }}
          - -o{{ Satellite_Organization }}
          - -aRHEL{{ ansible_distribution_major_version }}_AK
          - -L Default
          - --skip=puppet
          - --skip=foreman
          - --force
          - --install-katello-agent
          - --fqdn={{ dnsname }}
          - --legacy-purge
          - --legacy-login=migration
          - --legacy-password={{ Satellite5_Password }}

  when: ansible_distribution == "RedHat"
