---
# tasks file for host-registration
# check the os distribution family and version
- name: gather os distribution
  debug: msg="{{ item }}"
  with_items: 
  - "{{ ansible_distribution }}"
  - "{{ ansible_distribution_version }}"
  - "{{ ansible_distribution_major_version }}"

# install python2 if it is not installed
- name: check if the python is alraady installed
  shell: which python
  register: is_python_installed
  changed_when: false
  ignore_errors: true
  when: ansible_distribution_major_version == "8"

- name: install python3 on rhel 8 systems 
  block:
    - name: install python3
      yum:
        name: python36
        state: present

    - name: add python symbolic link to python3
      alternatives:
        name: python
        link: /usr/bin/python
        path: /usr/bin/python3.6
  when: ansible_distribution_major_version == "8" and is_python_installed.rc == 1 

# Download the bootstrap script from Satellite server and regidter rhel host
- name: Register to Satellite
  block:
    - name: Download bootstrap script
      get_url: 
        url: "{{ bootstrap_url }}"
        dest: /root/bootstrap.py
        mode: "0755"
        validate_certs: no

    - name: Run bootstrap script
      shell: /root/bootstrap.py -l admin -p {{ Password }} -s {{ Satellite_Server }} -o {{ Satellite_Organization }} -a "RHEL{{ ansible_distribution_major_version }}_AK" -L Default --skip-foreman --force --install-katello-agent --fqdn=$(hostname)
       register: bootstrap_log

    # - name: remove rhn subscription from rhel 7
    #   shell: mv /etc/sysconfig/rhn/systemid /root/systemid-bakup
    #   when: 
    # - debug:
    #   msg: "{{ bootstrap_log.stdout }}"
  when: ansible_distribution == "RedHat"
